# Generated by Django 5.2.12 on 2026-03-17 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_scheduleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarizeddocument',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='sharedmaterial',
            name='period',
            field=models.CharField(choices=[('General', 'General'), ('Prelims', 'Prelims'), ('Midterms', 'Midterms'), ('Finals', 'Finals')], default='General', max_length=20),
        ),
        migrations.AlterField(
            model_name='summarizeddocument',
            name='period',
            field=models.CharField(default='General', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='period',
            field=models.CharField(choices=[('General', 'General'), ('Prelims', 'Prelims'), ('Midterms', 'Midterms'), ('Finals', 'Finals')], default='General', max_length=20),
        ),
    ]
